
package dmit2015.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TemperatureConverter", targetNamespace = "http://xml.webservices.dmit2015/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TemperatureConverter {


    /**
     * 
     * @param kelvinValue
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "celsiusValue", targetNamespace = "")
    @RequestWrapper(localName = "kelvinToCelisus", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.KelvinToCelisus")
    @ResponseWrapper(localName = "kelvinToCelisusResponse", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.KelvinToCelisusResponse")
    public double kelvinToCelisus(
        @WebParam(name = "kelvinValue", targetNamespace = "")
        double kelvinValue);

    /**
     * 
     * @param fahrenheintValue
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "celsiusValue", targetNamespace = "")
    @RequestWrapper(localName = "fahrenheitToCelisus", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.FahrenheitToCelisus")
    @ResponseWrapper(localName = "fahrenheitToCelisusResponse", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.FahrenheitToCelisusResponse")
    public double fahrenheitToCelisus(
        @WebParam(name = "fahrenheintValue", targetNamespace = "")
        double fahrenheintValue);

    /**
     * 
     * @param celisusValue
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "kelvinValue", targetNamespace = "")
    @RequestWrapper(localName = "celisusToKelvin", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.CelisusToKelvin")
    @ResponseWrapper(localName = "celisusToKelvinResponse", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.CelisusToKelvinResponse")
    public double celisusToKelvin(
        @WebParam(name = "celisusValue", targetNamespace = "")
        double celisusValue);

    /**
     * 
     * @param celisusValue
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "fahrenheitValue", targetNamespace = "")
    @RequestWrapper(localName = "celisusToFahrenheit", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.CelisusToFahrenheit")
    @ResponseWrapper(localName = "celisusToFahrenheitResponse", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.CelisusToFahrenheitResponse")
    public double celisusToFahrenheit(
        @WebParam(name = "celisusValue", targetNamespace = "")
        double celisusValue);

    /**
     * 
     * @param kelvinValue
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "fahrenheitValue", targetNamespace = "")
    @RequestWrapper(localName = "kelvinToFahrenheit", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.KelvinToFahrenheit")
    @ResponseWrapper(localName = "kelvinToFahrenheitResponse", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.KelvinToFahrenheitResponse")
    public double kelvinToFahrenheit(
        @WebParam(name = "kelvinValue", targetNamespace = "")
        double kelvinValue);

    /**
     * 
     * @param fahrenheintValue
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "kelvinValue", targetNamespace = "")
    @RequestWrapper(localName = "fahrenheitToKelvin", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.FahrenheitToKelvin")
    @ResponseWrapper(localName = "fahrenheitToKelvinResponse", targetNamespace = "http://xml.webservices.dmit2015/", className = "dmit2015.soap.FahrenheitToKelvinResponse")
    public double fahrenheitToKelvin(
        @WebParam(name = "fahrenheintValue", targetNamespace = "")
        double fahrenheintValue);

}
