
package dmit2015.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShapeXmlWebService", targetNamespace = "http://localhost/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShapeXmlWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "areaOfCircle", targetNamespace = "http://localhost/", className = "dmit2015.soap.AreaOfCircle")
    @ResponseWrapper(localName = "areaOfCircleResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.AreaOfCircleResponse")
    public double areaOfCircle(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param radius
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "circumference", targetNamespace = "")
    @RequestWrapper(localName = "circumferenceOfCircle", targetNamespace = "http://localhost/", className = "dmit2015.soap.CircumferenceOfCircle")
    @ResponseWrapper(localName = "circumferenceOfCircleResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.CircumferenceOfCircleResponse")
    public double circumferenceOfCircle(
        @WebParam(name = "radius", targetNamespace = "")
        double radius);

    /**
     * 
     * @param radius
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "diameter", targetNamespace = "")
    @RequestWrapper(localName = "diameterOfCiricle", targetNamespace = "http://localhost/", className = "dmit2015.soap.DiameterOfCiricle")
    @ResponseWrapper(localName = "diameterOfCiricleResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.DiameterOfCiricleResponse")
    public double diameterOfCiricle(
        @WebParam(name = "radius", targetNamespace = "")
        double radius);

}
